name: Deployment Notification

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    
    steps:
      - name: Send deployment notification
        env:
          HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
          HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
          WORKFLOW_NAME: ${{ github.event.workflow_run.name }}
        run: |
          echo "Deployment completed successfully!"
          echo "Commit: $HEAD_SHA"
          echo "Branch: $HEAD_BRANCH"
          echo "Workflow: $WORKFLOW_NAME"
          # Add webhook notification here if needed
          # curl -X POST -H "Content-Type: application/json" \
          #   -d '{"text":"Deployment successful for commit $HEAD_SHA"}' \
          #   ${{ secrets.WEBHOOK_URL }}
