name: Deployment Notification

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    
    steps:
      - name: Send deployment notification
        env:
          COMMIT_SHA: ${{ github.event.workflow_run.head_sha }}
          BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
          WORKFLOW_NAME: ${{ github.event.workflow_run.name }}
        run: |
          echo "Deployment completed successfully!"
          echo "Commit: $COMMIT_SHA"
          echo "Branch: $BRANCH_NAME"
          echo "Workflow: $WORKFLOW_NAME"
          # Add webhook notification here if needed
          # curl -X POST -H "Content-Type: application/json" \
          #   -d "{\"text\":\"Deployment successful for commit $COMMIT_SHA\"}" \
          #   $WEBHOOK_URL
